# @author Daniel McCoy Stephenson
"""Generate the Traefik routers for every registered host (RFC 0006 §2, Option B).

TLS-ALPN-01 cannot issue a wildcard, and Traefik derives a certificate's
domains only from Host() matchers, so every host arcade answers gets its own
generated router: play.<base> (the API), each <slug>.play.<base>, and each
alias. All point at the one arcade service, which compose.yml declares with
labels (`arcade@docker`).

The output is a Traefik file-provider document. It is written as JSON, which
is valid YAML, so the gateway can drop it in its watched dynamic-config
directory as a .yml file; `--check` lets the gateway's CI prove the committed
file still matches games.yaml.
"""

import json

DEFAULTS = {
    "service": "arcade@docker",
    "entryPoint": "websecure",
    "certResolver": "letsencrypt",
    "middlewares": ("secure-headers@file",),
}

HEADER = (
    "# GENERATED by `python -m arcade routers` from games.yaml - do not edit by hand.\n"
    "# Regenerate after changing games.yaml; CI fails while this file is stale.\n"
)


def _router(host, options):
    return {
        "rule": "Host(`%s`)" % host,
        "entryPoints": [options["entryPoint"]],
        "service": options["service"],
        "middlewares": list(options["middlewares"]),
        "tls": {"certResolver": options["certResolver"]},
    }


def hosts(registry, domain):
    """(routerName, host) for every host arcade answers, in a stable order."""
    pairs = [("arcade-api", domain)]
    for game in registry:
        pairs.append(("arcade-%s" % game.slug, "%s.%s" % (game.slug, domain)))
        for index, alias in enumerate(game.aliases, start=1):
            pairs.append(("arcade-%s-alias-%d" % (game.slug, index), alias))
    return pairs


def generate(registry, domain, **overrides):
    options = dict(DEFAULTS)
    options.update(overrides)
    routers = {}
    for name, host in hosts(registry, domain):
        routers[name] = _router(host, options)
    return {"http": {"routers": routers}}


def render(registry, domain, **overrides):
    return HEADER + json.dumps(generate(registry, domain, **overrides), indent=2, sort_keys=True) + "\n"
