# @author Daniel McCoy Stephenson
"""Generate the Traefik routers for every registered host (RFC 0006 §2, Option B).

TLS-ALPN-01 cannot issue a wildcard, and Traefik derives a certificate's
domains only from Host() matchers, so every host arcade answers gets its own
generated router: play.<base> (the API), each <slug>.play.<base>, and each
alias. All point at the one arcade service, which compose.yml declares with
labels (`arcade@docker`).

Two ways to hand them to Traefik:

- the HTTP provider (what the gateway uses): arcade serves providerDocument()
  at /traefik/dynamic.json on its internal hostname, and Traefik polls it, so
  a games.yaml change becomes routers and certificates with no Traefik edit;
- a file-provider document from `python -m arcade routers` (JSON, which is
  valid YAML), with `--check` for a CI that commits it.
"""

import json

DEFAULTS = {
    "service": "arcade@docker",
    "entryPoint": "websecure",
    "certResolver": "letsencrypt",
    "middlewares": ("secure-headers@file",),
}

HEADER = (
    "# GENERATED by `python -m arcade routers` from games.yaml - do not edit by hand.\n"
    "# Regenerate after changing games.yaml; CI fails while this file is stale.\n"
)


def _router(host, options):
    return {
        "rule": "Host(`%s`)" % host,
        "entryPoints": [options["entryPoint"]],
        "service": options["service"],
        "middlewares": list(options["middlewares"]),
        "tls": {"certResolver": options["certResolver"]},
    }


def hosts(registry, domain, includeApi=True):
    """(routerName, host) for every host arcade answers, in a stable order.

    includeApi=False leaves out play.<base> itself, for a gateway that routes
    that one host with ordinary compose labels and takes only the games'
    routers from arcade (the HTTP provider, below)."""
    pairs = [("arcade-api", domain)] if includeApi else []
    for game in registry:
        pairs.append(("arcade-%s" % game.slug, "%s.%s" % (game.slug, domain)))
        for index, alias in enumerate(game.aliases, start=1):
            pairs.append(("arcade-%s-alias-%d" % (game.slug, index), alias))
    return pairs


def generate(registry, domain, includeApi=True, **overrides):
    options = dict(DEFAULTS)
    options.update(overrides)
    routers = {}
    for name, host in hosts(registry, domain, includeApi=includeApi):
        routers[name] = _router(host, options)
    return {"http": {"routers": routers}}


def providerDocument(registry, domain, **overrides):
    """The JSON Traefik's HTTP provider polls from arcade: every game's
    routers, without play.<base> (routed by compose labels). An empty registry
    still yields a well-formed, empty document."""
    generated = generate(registry, domain, includeApi=False, **overrides)
    if not generated["http"]["routers"]:
        return {}
    return generated


def render(registry, domain, **overrides):
    return HEADER + json.dumps(generate(registry, domain, **overrides), indent=2, sort_keys=True) + "\n"
